name: characters-counter-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run isort
        run: isort --check --diff .
      - name: Run black
        run: black --check --diff .
      - name: Run flake8
        run: flake8
      - name: Run mypy
        run: mypy .
      - name: Run tests with Pytest
        run: |
          pytest --cov tests/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
